name: Terraform Safe Cleanup

on:
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      # 3️⃣ Delete EC2 Instances
      - name: Delete EC2 Instances
        run: |
          for NAME in web1 web2; do
            INSTANCE_ID=$(aws ec2 describe-instances \
              --filters "Name=tag:Name,Values=$NAME" \
              --query "Reservations[].Instances[].InstanceId" --output text)
            if [ -n "$INSTANCE_ID" ]; then
              echo "Terminating instance $NAME ($INSTANCE_ID)"
              aws ec2 terminate-instances --instance-ids $INSTANCE_ID
              aws ec2 wait instance-terminated --instance-ids $INSTANCE_ID
            fi
          done

      # 4️⃣ Delete Security Group
      - name: Delete Security Group
        run: |
          SG_ID=$(aws ec2 describe-security-groups \
            --filters "Name=group-name,Values=ssh-sg" \
            --query "SecurityGroups[].GroupId" --output text)
          if [ -n "$SG_ID" ]; then
            echo "Deleting Security Group ssh-sg ($SG_ID)"
            aws ec2 delete-security-group --group-id $SG_ID
          fi

      # 5️⃣ Delete Route Table Association
      - name: Delete Route Table Association
        run: |
          SUBNET_ID=$(aws ec2 describe-subnets \
            --filters "Name=tag:Name,Values=main-subnet" \
            --query "Subnets[].SubnetId" --output text)
          RT_ID=$(aws ec2 describe-route-tables \
            --filters "Name=tag:Name,Values=public-rt" \
            --query "RouteTables[].RouteTableId" --output text)
          ASSOC_ID=$(aws ec2 describe-route-tables \
            --route-table-ids $RT_ID \
            --query "RouteTables[].Associations[?SubnetId=='$SUBNET_ID'].RouteTableAssociationId" \
            --output text)
          if [ -n "$ASSOC_ID" ]; then
            aws ec2 disassociate-route-table --association-id $ASSOC_ID
            echo "Disassociated route table from subnet"
          fi

      # 6️⃣ Delete Route Table
      - name: Delete Route Table
        run: |
          RT_ID=$(aws ec2 describe-route-tables \
            --filters "Name=tag:Name,Values=public-rt" \
            --query "RouteTables[].RouteTableId" --output text)
          if [ -n "$RT_ID" ]; then
            aws ec2 delete-route-table --route-table-id $RT_ID
          fi

      # 7️⃣ Delete Internet Gateway
      - name: Delete Internet Gateway
        run: |
          IGW_ID=$(aws ec2 describe-internet-gateways \
            --filters "Name=tag:Name,Values=main-igw" \
            --query "InternetGateways[].InternetGatewayId" --output text)
          if [ -n "$IGW_ID" ]; then
            VPC_ID=$(aws ec2 describe-internet-gateways --internet-gateway-ids $IGW_ID \
                     --query "InternetGateways[0].Attachments[0].VpcId" --output text)
            if [ -n "$VPC_ID" ]; then
              aws ec2 detach-internet-gateway --internet-gateway-id $IGW_ID --vpc-id $VPC_ID
            fi
            aws ec2 delete-internet-gateway --internet-gateway-id $IGW_ID
          fi

      # 8️⃣ Delete Subnet
      - name: Delete Subnet
        run: |
          SUBNET_ID=$(aws ec2 describe-subnets \
            --filters "Name=tag:Name,Values=main-subnet" \
            --query "Subnets[].SubnetId" --output text)
          if [ -n "$SUBNET_ID" ]; then
            aws ec2 delete-subnet --subnet-id $SUBNET_ID
          fi

      # 9️⃣ Delete VPC
      - name: Delete VPC
        run: |
          VPC_ID=$(aws ec2 describe-vpcs \
            --filters "Name=tag:Name,Values=main-vpc" \
            --query "Vpcs[].VpcId" --output text)
          if [ -n "$VPC_ID" ]; then
            aws ec2 delete-vpc --vpc-id $VPC_ID
          fi

      # 🔟 Delete Key Pair
      - name: Delete Key Pair
        run: |
          KEY_NAME="host-tf"
          aws ec2 delete-key-pair --key-name $KEY_NAME || echo "Key pair $KEY_NAME does not exist"
